# Generated by Django 5.0.7 on 2024-07-16 04:40

import datetime
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='newsItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('news_date', models.DateField(default=datetime.date.today)),
                ('content', wagtail.fields.StreamField([('quote_block', wagtail.blocks.StructBlock([('quote', wagtail.blocks.BlockQuoteBlock(help_text="Enter the text you'd like to appear in quotation marks", required=True)), ('attribution', wagtail.blocks.CharBlock(help_text='attribute the quote to someone', required=False))], icon='openquote')), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True)),
                ('news_image', models.ForeignKey(help_text='upload an image for the bio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
