# Generated by Django 5.0.10 on 2025-01-13 05:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_newsindexpage_blogindexpage_blogitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='content',
            field=wagtail.fields.StreamField([('quote_block', 2), ('paragraph', 3), ('code_snippet', 4)], blank=True, block_lookup={0: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': "Enter the text you'd like to appear in quotation marks", 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'attribute the quote to someone', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('quote', 0), ('attribution', 1)]], {'icon': 'openquote'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {})}),
        ),
    ]
