# Generated by Django 6.0 on 2026-06-21 17:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogitem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='content',
            field=wagtail.fields.StreamField([('quote_block', 2), ('paragraph', 3), ('image', 4), ('code_snippet', 5)], blank=True, block_lookup={0: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': "Enter the text you'd like to appear in quotation marks", 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'attribute the quote to someone', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('quote', 0), ('attribution', 1)]], {'icon': 'openquote'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {})}),
        ),
    ]
