# Generated by Django 6.0 on 2026-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogitem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='blog_teaser',
            field=models.TextField(blank=True, help_text='Optional blog teaser. If null the first sentence of the post will be used.', max_length=400, null=True),
        ),
    ]
